package com.group18.po;
// Generated 2021-11-27 1:43:04 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClientQualification generated by hbm2java
 */
@Entity
@Table(name = "client_qualification", catalog = "parkingsafesdb")
public class ClientQualification implements java.io.Serializable {

	private int qid;
	private Client client;
	private byte[] image;
	private Boolean qualification;
	private String address;

	public ClientQualification() {
	}

	public ClientQualification(int qid, Client client) {
		this.qid = qid;
		this.client = client;
	}

	public ClientQualification(int qid, Client client, byte[] image, Boolean qualification, String address) {
		this.qid = qid;
		this.client = client;
		this.image = image;
		this.qualification = qualification;
		this.address = address;
	}

	@Id

	@Column(name = "qid", unique = true, nullable = false)
	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "qualification")
	public Boolean getQualification() {
		return this.qualification;
	}

	public void setQualification(Boolean qualification) {
		this.qualification = qualification;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
