package com.group18.po;
// Generated 2021-11-27 1:43:04 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dealing generated by hbm2java
 */
@Entity
@Table(name = "dealing", catalog = "parkingsafesdb")
public class Dealing implements java.io.Serializable {

	private int no;
	private Parking parking;
	private Client client;
	private User user;
	private String name;
	private String phone;
	private Date time;
	private Boolean pay;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Dealing() {
	}

	public Dealing(int no, Parking parking, Client client, User user) {
		this.no = no;
		this.parking = parking;
		this.client = client;
		this.user = user;
	}

	public Dealing(int no, Parking parking, Client client, User user, String name, String phone, Date time, Boolean pay,
			Set<Payment> payments) {
		this.no = no;
		this.parking = parking;
		this.client = client;
		this.user = user;
		this.name = name;
		this.phone = phone;
		this.time = time;
		this.pay = pay;
		this.payments = payments;
	}

	@Id

	@Column(name = "no", unique = true, nullable = false)
	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false)
	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 26)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "pay")
	public Boolean getPay() {
		return this.pay;
	}

	public void setPay(Boolean pay) {
		this.pay = pay;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealing")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
