package com.group18.po;
// Generated 2021-11-27 1:43:04 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parking generated by hbm2java
 */
@Entity
@Table(name = "parking", catalog = "parkingsafesdb")
public class Parking implements java.io.Serializable {

	private int pid;
	private Boolean sublevel;
	private Integer area;
	private Integer priceUnit;
	private Boolean type;
	private String address;
	private Set<Dealing> dealings = new HashSet<Dealing>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);

	public Parking() {
	}

	public Parking(int pid) {
		this.pid = pid;
	}

	public Parking(int pid, Boolean sublevel, Integer area, Integer priceUnit, Boolean type, String address,
			Set<Dealing> dealings, Set<Payment> payments, Set<Reservation> reservations) {
		this.pid = pid;
		this.sublevel = sublevel;
		this.area = area;
		this.priceUnit = priceUnit;
		this.type = type;
		this.address = address;
		this.dealings = dealings;
		this.payments = payments;
		this.reservations = reservations;
	}

	@Id

	@Column(name = "pid", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "sublevel")
	public Boolean getSublevel() {
		return this.sublevel;
	}

	public void setSublevel(Boolean sublevel) {
		this.sublevel = sublevel;
	}

	@Column(name = "area")
	public Integer getArea() {
		return this.area;
	}

	public void setArea(Integer area) {
		this.area = area;
	}

	@Column(name = "price_unit")
	public Integer getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(Integer priceUnit) {
		this.priceUnit = priceUnit;
	}

	@Column(name = "type")
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parking")
	public Set<Dealing> getDealings() {
		return this.dealings;
	}

	public void setDealings(Set<Dealing> dealings) {
		this.dealings = dealings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parking")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parking")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
