package com.group18.po;
// Generated 2021-11-27 1:43:04 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentId generated by hbm2java
 */
@Embeddable
public class PaymentId implements java.io.Serializable {

	private int no;
	private int cid;
	private int pid;

	public PaymentId() {
	}

	public PaymentId(int no, int cid, int pid) {
		this.no = no;
		this.cid = cid;
		this.pid = pid;
	}

	@Column(name = "no", nullable = false)
	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	@Column(name = "cid", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "pid", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentId))
			return false;
		PaymentId castOther = (PaymentId) other;

		return (this.getNo() == castOther.getNo()) && (this.getCid() == castOther.getCid())
				&& (this.getPid() == castOther.getPid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNo();
		result = 37 * result + this.getCid();
		result = 37 * result + this.getPid();
		return result;
	}

}
