package com.group18.po;
// Generated 2021-11-27 1:43:04 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "parkingsafesdb")
public class Reservation implements java.io.Serializable {

	private ReservationId id;
	private Parking parking;
	private Client client;
	private Date time;

	public Reservation() {
	}

	public Reservation(ReservationId id, Parking parking, Client client) {
		this.id = id;
		this.parking = parking;
		this.client = client;
	}

	public Reservation(ReservationId id, Parking parking, Client client, Date time) {
		this.id = id;
		this.parking = parking;
		this.client = client;
		this.time = time;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cid", column = @Column(name = "cid", nullable = false)),
			@AttributeOverride(name = "pid", column = @Column(name = "pid", nullable = false)) })
	public ReservationId getId() {
		return this.id;
	}

	public void setId(ReservationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false, insertable = false, updatable = false)
	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid", nullable = false, insertable = false, updatable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 26)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
