package com.group18.po;
// Generated 2021-11-27 1:43:04 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "parkingsafesdb")
public class User implements java.io.Serializable {

	private int uid;
	private String username;
	private String password;
	private Boolean identity;
	private UserInformation userInformation;
	private Set<UserQualification> userQualifications = new HashSet<UserQualification>(0);
	private Set<Dealing> dealings = new HashSet<Dealing>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public User() {
	}

	public User(int uid) {
		this.uid = uid;
	}

	public User(int uid, String username, String password, Boolean identity, UserInformation userInformation,
		 Set<UserQualification> userQualifications, Set<Dealing> dealings,
			Set<Payment> payments) {
		this.uid = uid;
		this.username = username;
		this.password = password;
		this.identity = identity;
		this.userInformation = userInformation;
		this.userInformation = userInformation;
		this.userQualifications = userQualifications;
		this.dealings = dealings;
		this.payments = payments;
	}

	@Id

	@Column(name = "uid", unique = true, nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "identity")
	public Boolean getIdentity() {
		return this.identity;
	}

	public void setIdentity(Boolean identity) {
		this.identity = identity;
	}


	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public UserInformation getUserInformation() {
		return this.userInformation;
	}

	public void setUserInformation(UserInformation userInformation) {
		this.userInformation = userInformation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserQualification> getUserQualifications() {
		return this.userQualifications;
	}

	public void setUserQualifications(Set<UserQualification> userQualifications) {
		this.userQualifications = userQualifications;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Dealing> getDealings() {
		return this.dealings;
	}

	public void setDealings(Set<Dealing> dealings) {
		this.dealings = dealings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
