package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

/**
 * ClientQualification generated by hbm2java
 */
public class ClientQualification implements java.io.Serializable {

	private Integer qid;
	private Client client;
	private byte[] image;
	private Boolean qualification;
	private String adress;

	public ClientQualification() {
	}

	public ClientQualification(Client client) {
		this.client = client;
	}

	public ClientQualification(Client client, byte[] image, Boolean qualification, String adress) {
		this.client = client;
		this.image = image;
		this.qualification = qualification;
		this.adress = adress;
	}

	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Boolean getQualification() {
		return this.qualification;
	}

	public void setQualification(Boolean qualification) {
		this.qualification = qualification;
	}

	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

}
