package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * ClientInformation generated by hbm2java
 */
public class ClientInformation implements java.io.Serializable {

	private int cid;
	private Client client;
	private String name;
	private Boolean sex;
	private Integer age;
	private Date birthday;
	private String email;
	private String phone;

	public ClientInformation() {
	}

	public ClientInformation(Client client) {
		this.client = client;
	}

	public ClientInformation(Client client, String name, Boolean sex, Integer age, Date birthday, String email,
			String phone) {
		this.client = client;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.birthday = birthday;
		this.email = email;
		this.phone = phone;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
