package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;
/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer cid;
	private String username;
	private String password;
	private ClientInformation clientInformation;
	private Set clientQualifications = new HashSet(0);
	private Set dealings = new HashSet(0);
	private Set reservations = new HashSet(0);
	private Set clientQualifications_1 = new HashSet(0);
	private Set payments = new HashSet(0);

	public Client() {
	}

	public Client(String username, String password, ClientInformation clientInformation, Set clientQualifications,
			Set dealings, Set reservations, Set clientQualifications_1, Set payments) {
		this.username = username;
		this.password = password;
		this.clientInformation = clientInformation;
		this.clientQualifications = clientQualifications;
		this.dealings = dealings;
		this.reservations = reservations;
		this.clientQualifications_1 = clientQualifications_1;
		this.payments = payments;
		this.clientInformation = clientInformation;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public ClientInformation getClientInformation() {
		return this.clientInformation;
	}

	public void setClientInformation(ClientInformation clientInformation) {
		this.clientInformation = clientInformation;
	}

	public Set getClientQualifications() {
		return this.clientQualifications;
	}

	public void setClientQualifications(Set clientQualifications) {
		this.clientQualifications = clientQualifications;
	}

	public Set getDealings() {
		return this.dealings;
	}

	public void setDealings(Set dealings) {
		this.dealings = dealings;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

	public Set getClientQualifications_1() {
		return this.clientQualifications_1;
	}

	public void setClientQualifications_1(Set clientQualifications_1) {
		this.clientQualifications_1 = clientQualifications_1;
	}

	public Set getPayments() {
		return this.payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}
}
