package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dealing generated by hbm2java
 */
public class Dealing implements java.io.Serializable {

	private int no;
	private Client client;
	private Parking parking;
	private User user;
	private String name;
	private String phone;
	private Date time;
	private Boolean pay;
	private Set payments = new HashSet(0);

	public Dealing() {
	}

	public Dealing(int no, Client client, Parking parking, User user) {
		this.no = no;
		this.client = client;
		this.parking = parking;
		this.user = user;
	}

	public Dealing(int no, Client client, Parking parking, User user, String name, String phone, Date time, Boolean pay,
			Set payments) {
		this.no = no;
		this.client = client;
		this.parking = parking;
		this.user = user;
		this.name = name;
		this.phone = phone;
		this.time = time;
		this.pay = pay;
		this.payments = payments;
	}

	public int getNo() {
		return this.no;
	}

	public void setNo(int no) {
		this.no = no;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Boolean getPay() {
		return this.pay;
	}

	public void setPay(Boolean pay) {
		this.pay = pay;
	}

	public Set getPayments() {
		return this.payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}

}
