package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Parking generated by hbm2java
 */
public class Parking implements java.io.Serializable {

	private int pid;
	private Boolean sublevel;
	private Integer area;
	private Integer priceUnit;
	private Boolean type;
	private String address;
	private Set dealings = new HashSet(0);
	private Set payments = new HashSet(0);
	private Set reservations = new HashSet(0);

	public Parking() {
	}

	public Parking(int pid) {
		this.pid = pid;
	}

	public Parking(int pid, Boolean sublevel, Integer area, Integer priceUnit, Boolean type, String address,
			Set dealings, Set payments, Set reservations) {
		this.pid = pid;
		this.sublevel = sublevel;
		this.area = area;
		this.priceUnit = priceUnit;
		this.type = type;
		this.address = address;
		this.dealings = dealings;
		this.payments = payments;
		this.reservations = reservations;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public Boolean getSublevel() {
		return this.sublevel;
	}

	public void setSublevel(Boolean sublevel) {
		this.sublevel = sublevel;
	}

	public Integer getArea() {
		return this.area;
	}

	public void setArea(Integer area) {
		this.area = area;
	}

	public Integer getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(Integer priceUnit) {
		this.priceUnit = priceUnit;
	}

	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getDealings() {
		return this.dealings;
	}

	public void setDealings(Set dealings) {
		this.dealings = dealings;
	}

	public Set getPayments() {
		return this.payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
