package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private PaymentId id;
	private Client client;
	private Dealing dealing;
	private Parking parking;
	private User user;
	private Date time;
	private Boolean pay;
	private BigDecimal paid;
	private BigDecimal unpaid;
	private Date deadline;

	public Payment() {
	}

	public Payment(PaymentId id, Client client, Dealing dealing, Parking parking, User user) {
		this.id = id;
		this.client = client;
		this.dealing = dealing;
		this.parking = parking;
		this.user = user;
	}

	public Payment(PaymentId id, Client client, Dealing dealing, Parking parking, User user, Date time, Boolean pay,
			BigDecimal paid, BigDecimal unpaid, Date deadline) {
		this.id = id;
		this.client = client;
		this.dealing = dealing;
		this.parking = parking;
		this.user = user;
		this.time = time;
		this.pay = pay;
		this.paid = paid;
		this.unpaid = unpaid;
		this.deadline = deadline;
	}

	public PaymentId getId() {
		return this.id;
	}

	public void setId(PaymentId id) {
		this.id = id;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Dealing getDealing() {
		return this.dealing;
	}

	public void setDealing(Dealing dealing) {
		this.dealing = dealing;
	}

	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Boolean getPay() {
		return this.pay;
	}

	public void setPay(Boolean pay) {
		this.pay = pay;
	}

	public BigDecimal getPaid() {
		return this.paid;
	}

	public void setPaid(BigDecimal paid) {
		this.paid = paid;
	}

	public BigDecimal getUnpaid() {
		return this.unpaid;
	}

	public void setUnpaid(BigDecimal unpaid) {
		this.unpaid = unpaid;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

}
