package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private ReservationId id;
	private Client client;
	private Parking parking;
	private Date time;

	public Reservation() {
	}

	public Reservation(ReservationId id, Client client, Parking parking) {
		this.id = id;
		this.client = client;
		this.parking = parking;
	}

	public Reservation(ReservationId id, Client client, Parking parking, Date time) {
		this.id = id;
		this.client = client;
		this.parking = parking;
		this.time = time;
	}

	public ReservationId getId() {
		return this.id;
	}

	public void setId(ReservationId id) {
		this.id = id;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Parking getParking() {
		return this.parking;
	}

	public void setParking(Parking parking) {
		this.parking = parking;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
