package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

/**
 * ReservationId generated by hbm2java
 */
public class ReservationId implements java.io.Serializable {

	private int cid;
	private int pid;

	public ReservationId() {
	}

	public ReservationId(int cid, int pid) {
		this.cid = cid;
		this.pid = pid;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservationId))
			return false;
		ReservationId castOther = (ReservationId) other;

		return (this.getCid() == castOther.getCid()) && (this.getPid() == castOther.getPid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCid();
		result = 37 * result + this.getPid();
		return result;
	}

}
