package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private String username;
	private String password;
	private Boolean identity;
	private UserInformation userInformation;
	private Set userQualifications = new HashSet(0);
	private Set dealings = new HashSet(0);
	private Set payments = new HashSet(0);
	private Set userQualifications_1 = new HashSet(0);

	public User() {
	}

	public User(String username, String password, Boolean identity, UserInformation userInformation,
		    Set userQualifications, Set dealings, Set payments,
			Set userQualifications_1) {
		this.username = username;
		this.password = password;
		this.identity = identity;
		this.userInformation = userInformation;
		this.userInformation = userInformation;
		this.userQualifications = userQualifications;
		this.dealings = dealings;
		this.payments = payments;
		this.userQualifications_1 = userQualifications_1;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getIdentity() {
		return this.identity;
	}

	public void setIdentity(Boolean identity) {
		this.identity = identity;
	}

	public UserInformation getUserInformation() {
		return this.userInformation;
	}

	public void setUserInformation(UserInformation userInformation) {
		this.userInformation = userInformation;
	}

	public Set getUserQualifications() {
		return this.userQualifications;
	}

	public void setUserQualifications(Set userQualifications) {
		this.userQualifications = userQualifications;
	}

	public Set getDealings() {
		return this.dealings;
	}

	public void setDealings(Set dealings) {
		this.dealings = dealings;
	}

	public Set getPayments() {
		return this.payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}

	public Set getUserQualifications_1() {
		return this.userQualifications_1;
	}

	public void setUserQualifications_1(Set userQualifications_1) {
		this.userQualifications_1 = userQualifications_1;
	}

}
