package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

/**
 * UserInformation generated by hbm2java
 */
public class UserInformation implements java.io.Serializable {

	private int uid;
	private User user;
	private String name;
	private String address;
	private String contactsName;
	private String contactsPhone;
	private String intro;

	public UserInformation() {
	}

	public UserInformation(User user) {
		this.user = user;
	}

	public UserInformation(User user, String name, String address, String contactsName, String contactsPhone,
			String intro) {
		this.user = user;
		this.name = name;
		this.address = address;
		this.contactsName = contactsName;
		this.contactsPhone = contactsPhone;
		this.intro = intro;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactsName() {
		return this.contactsName;
	}

	public void setContactsName(String contactsName) {
		this.contactsName = contactsName;
	}

	public String getContactsPhone() {
		return this.contactsPhone;
	}

	public void setContactsPhone(String contactsPhone) {
		this.contactsPhone = contactsPhone;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

}
