package po;

// default package
// Generated 2021-11-25 22:16:02 by Hibernate Tools 5.3.0.Beta2

/**
 * UserQualification generated by hbm2java
 */
public class UserQualification implements java.io.Serializable {

	private int qid;
	private User user;
	private byte[] image;
	private Boolean qualification;

	public UserQualification() {
	}

	public UserQualification(int qid, User user) {
		this.qid = qid;
		this.user = user;
	}

	public UserQualification(int qid, User user, byte[] image, Boolean qualification) {
		this.qid = qid;
		this.user = user;
		this.image = image;
		this.qualification = qualification;
	}

	public int getQid() {
		return this.qid;
	}

	public void setQid(int qid) {
		this.qid = qid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Boolean getQualification() {
		return this.qualification;
	}

	public void setQualification(Boolean qualification) {
		this.qualification = qualification;
	}

}
